name: pizza_delivery
description: "Livraison Pizza"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

  firebase_core: ^2.32.0
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  meta: ^1.16.0
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios : true
  image_path: "assets/1.png"

  assets:
    - assets/
