name: pizza_repository
description: Le dépôt qui gère les pizzas
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  rxdart: ^0.28.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true